### ISSUE TITLE
running the example somehow requires torch and tensorboardX

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#23] opened 2019-04-16 08:34 UTC
with a clean checkout and environement, I need to install torch and tensorboardX to run the mnist_tf example.

even after checking out an older version (e8e96bba2b33ac47cc01aa6e03085d8fe0f109d3)

**Comment by pesser** [comment] 2019-04-16 09:06
yup, my bad for merging #14. The problem is here: https://github.com/pesser/edflow/blob/4c8400aa16dae4548995c60ceb861db4d72ebf86/edflow/iterators/model_iterator.py#L6 but should be fixed with #20

**Closed as completed** 2019-06-03 12:01 UTC
Labels: bug
